#!/bin/bash
set -e

commit=$(git log -1 --format="%h" 2>/dev/null || echo no-commit)
exec 1> >(logger -s -p user.notice -t $0-rcran-$commit 2>&1)
exec 2> >(logger -s -p user.error -t $0-rcran-$commit)

# Default behavior is to do everything from scratch.
# The --use-cache option is useful if you're iterating on a broken build.
if [[ "$1" ==  "--use-cache" ]]; then
    docker build --rm --cpu-period=100000 --cpu-quota=200000 -t kaggle/rcran-build .
else
    docker build --pull --rm --no-cache --cpu-period=100000 --cpu-quota=200000 -t kaggle/rcran-build .
fi
